# Generated by Django 6.1 on 2026-09-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signaling', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='signalingintervention',
            constraint=models.UniqueConstraint(fields=('signaling_point', 'type'), name='unique_intervention_type_per_signaling_point'),
        ),
    ]
