# Generated by Django 6.1 on 2026-09-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signaling', '0002_signalingintervention_unique_intervention_type_per_signaling_point'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signalingintervention',
            name='unique_intervention_type_per_signaling_point',
        ),
        migrations.AlterField(
            model_name='signalingintervention',
            name='type',
            field=models.CharField(choices=[('TRAFFIC_LIGHT', 'Semáforo'), ('PEDESTRIAN_CROSSING', 'Travessia segura'), ('MINI_ROUNDABOUT', 'Minirrotatória'), ('RIGHT_OF_WAY_REVERSAL', 'Inversão de Pref. Passagem'), ('TRAFFIC_FLOW_CHANGE', 'Alteração de circulação'), ('PEDESTRIAN_REFUGE', 'Refúgios para pedestres'), ('NO_PARKING', 'Proibido estacionar'), ('GEOMETRY_ADJUSTMENT', 'Adequação na geometria'), ('SPEED_REDUCTION', 'Redução de velocidade'), ('VERTICAL_HORIZONTAL_SIGNALING', 'Sinalizações verticais e horizontais'), ('LOW_VISIBILITY', 'Visibilidade prejudicada'), ('R1', 'R-1'), ('STREET_LIGHTING', 'Iluminação'), ('SPEED_BUMP', 'Lombada'), ('R5A', 'R-5a'), ('R5B', 'R-5b'), ('R4A', 'R-4a'), ('R24A', 'R-24a'), ('R6C', 'R-6c'), ('R6A', 'R-6a'), ('RAISED_CROSSWALK', 'Faixa elevada')], max_length=30),
        ),
    ]
