# Generated by Django 6.1 on 2026-09-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signaling', '0003_remove_signalingintervention_unique_intervention_type_per_signaling_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalingintervention',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
