# Generated by Django 6.1 on 2026-09-11 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signaling', '0004_signalingintervention_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalingpoint',
            name='search_radius_meters',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
