# Generated by Django 6.1 on 2026-10-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signaling', '0005_signalingpoint_search_radius_meters'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalingPointProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_code', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5')], max_length=2)),
                ('solution_code', models.CharField(choices=[('P1A', 'P1A'), ('P1B', 'P1B'), ('P2A', 'P2A'), ('P2B', 'P2B'), ('P3A', 'P3A'), ('P3B', 'P3B'), ('P3C', 'P3C'), ('P3D', 'P3D'), ('P4A', 'P4A'), ('P4B', 'P4B'), ('P4C', 'P4C'), ('P4D', 'P4D'), ('P4E', 'P4E'), ('P5A', 'P5A'), ('P5B', 'P5B'), ('P5C', 'P5C'), ('P5D', 'P5D')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signaling_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='signaling.signalingpoint')),
            ],
            options={
                'ordering': ['problem_code'],
                'constraints': [models.UniqueConstraint(fields=('signaling_point', 'problem_code'), name='unique_problem_per_signaling_point'), models.CheckConstraint(condition=models.Q(models.Q(('problem_code', 'P1'), ('solution_code__in', ('P1A', 'P1B'))), models.Q(('problem_code', 'P2'), ('solution_code__in', ('P2A', 'P2B'))), models.Q(('problem_code', 'P3'), ('solution_code__in', ('P3A', 'P3B', 'P3C', 'P3D'))), models.Q(('problem_code', 'P4'), ('solution_code__in', ('P4A', 'P4B', 'P4C', 'P4D', 'P4E'))), models.Q(('problem_code', 'P5'), ('solution_code__in', ('P5A', 'P5B', 'P5C', 'P5D'))), _connector='OR'), name='valid_signaling_problem_solution')],
            },
        ),
    ]
