# Generated by Django 6.1 on 2026-10-02 13:14

import django.db.models.deletion
from django.db import migrations, models


def copy_solutions(apps, schema_editor):
    Problem = apps.get_model("signaling", "SignalingPointProblem")
    Solution = apps.get_model("signaling", "SignalingPointProblemSolution")
    alias = schema_editor.connection.alias
    for problem in Problem.objects.using(alias).iterator():
        Solution.objects.using(alias).create(
            problem_id=problem.pk, solution_code=problem.solution_code,
        )


def restore_single_solution(apps, schema_editor):
    from django.db.migrations.exceptions import IrreversibleError
    Problem = apps.get_model("signaling", "SignalingPointProblem")
    Solution = apps.get_model("signaling", "SignalingPointProblemSolution")
    alias = schema_editor.connection.alias
    for problem in Problem.objects.using(alias).iterator():
        codes = list(Solution.objects.using(alias).filter(
            problem_id=problem.pk,
        ).values_list("solution_code", flat=True))
        if len(codes) != 1:
            raise IrreversibleError("Cannot restore single-solution schema without losing data.")
        Problem.objects.using(alias).filter(pk=problem.pk).update(solution_code=codes[0])


class Migration(migrations.Migration):

    dependencies = [
        ('signaling', '0006_signalingpointproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalingPointProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_code', models.CharField(choices=[('P1A', 'P1A'), ('P1B', 'P1B'), ('P2A', 'P2A'), ('P2B', 'P2B'), ('P3A', 'P3A'), ('P3B', 'P3B'), ('P3C', 'P3C'), ('P3D', 'P3D'), ('P4A', 'P4A'), ('P4B', 'P4B'), ('P4C', 'P4C'), ('P4D', 'P4D'), ('P4E', 'P4E'), ('P5A', 'P5A'), ('P5B', 'P5B'), ('P5C', 'P5C'), ('P5D', 'P5D')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['solution_code'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='signalingpointproblem',
            name='valid_signaling_problem_solution',
        ),
        migrations.AddConstraint(
            model_name='signalingpointproblem',
            constraint=models.CheckConstraint(condition=models.Q(('problem_code__in', ['P1', 'P2', 'P3', 'P4', 'P5'])), name='valid_signaling_problem_code'),
        ),
        migrations.AddField(
            model_name='signalingpointproblemsolution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='signaling.signalingpointproblem'),
        ),
        # Nullable only during conversion, so reverse can restore values before NOT NULL.
        migrations.AlterField(
            model_name='signalingpointproblem',
            name='solution_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.RunPython(copy_solutions, restore_single_solution),
        migrations.RemoveField(
            model_name='signalingpointproblem',
            name='solution_code',
        ),
        migrations.AddConstraint(
            model_name='signalingpointproblemsolution',
            constraint=models.UniqueConstraint(fields=('problem', 'solution_code'), name='unique_solution_per_point_problem'),
        ),
        migrations.AddConstraint(
            model_name='signalingpointproblemsolution',
            constraint=models.CheckConstraint(condition=models.Q(('solution_code__in', ['P1A', 'P1B', 'P2A', 'P2B', 'P3A', 'P3B', 'P3C', 'P3D', 'P4A', 'P4B', 'P4C', 'P4D', 'P4E', 'P5A', 'P5B', 'P5C', 'P5D'])), name='valid_point_problem_solution_code'),
        ),
    ]
